version: 2.1

references:
  node_defaults: &node_defaults
    working_directory: ~/app
    docker:
      - image: circleci/node:12

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  checkout_code:
    <<: *node_defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/app
          paths:
            - .

  build:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/app
      - restore-cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      - run: npm install
      - save-cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/app/node_modules
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules

  test_unit:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: npm run test:app

  test_lint:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: npm run test:lint

  test_markdown:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: npm run test:markdown

  test_sonar:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/app
      - sonarcloud/scan

  deploy:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/app
      - deploy:
          name: Deploy to npm
          command: npm run semantic-release

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - test_unit:
          requires:
            - build
      - test_lint:
          requires:
            - build
      - test_markdown:
          requires:
            - build
      - test_sonar:
          context: SonarCloud
          requires:
            - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - test_unit
            - test_lint
            - test_markdown
