version: 2.1

references:
  node_defaults: &node_defaults
    working_directory: ~/app
    docker:
      - image: cimg/node:18.17

jobs:
  checkout_code:
    <<: *node_defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/app
          paths:
            - .

  build:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/app
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/app/node_modules
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules

  test_unit:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: npm run test:app

  test_lint:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: npm run test:lint
  
  test_types:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: npm run typecheck

  test_markdown:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: npm run test:markdown

  deploy:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Deploy to npm
          command: npm run semantic-release

workflows:
  test_and_deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - test_unit:
          requires:
            - build
      - test_lint:
          requires:
            - build
      - test_markdown:
          requires:
            - build
      - test_types:
          requires:
            - build
      - deploy:
          context:
            - semantic-release
          filters:
            branches:
              only:
                - master
                - beta
          requires:
            - test_types
            - test_unit
            - test_lint
            - test_markdown
